### ISSUE TITLE
SDK should be proxy aware

### ISSUE THREAD

**Issue by rjdkolb** [Azure/azure-kusto-java#29]
The current implementation (0.2.0) does not work behind a proxy.

Steps to recreate
1) Use a computer behind a proxy that does not have internet access
2) checkout azure-kusto-java
3) run "mvn install"
4) cd samples
5) (edit the https.proxyHost and https.proxyPort to match your environment)  mvn exec:java -Dhttps.proxyHost=localhost -Dhttps.proxyPort=8888 -Dexec.mainClass="Query"

result:
[pool-1-thread-1] INFO com.microsoft.aad.adal4j.UserDiscoveryRequest - [Correlation ID: null] Sent (null) Correlation Id is not same as received (null).
[pool-1-thread-1] INFO com.microsoft.aad.adal4j.AuthenticationAuthority - [Correlation ID: 0a60824f-7bf6-40c3-bff5-fa0862e01842] Instance discovery was successful
org.apache.http.conn.HttpHostConnectException: Connect to bmw.kusto.windows.net:443 [bmw.kusto.windows.net/40.112.88.57] failed: Connection timed out: connect
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at com.microsoft.azure.kusto.data.Utils.post(Utils.java:40)
        at com.microsoft.azure.kusto.data.KustoClient.execute(KustoClient.java:40)
        at com.microsoft.azure.kusto.data.KustoClient.execute(KustoClient.java:30)
        at Query.main(Query.java:21)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection timed out: connect

The fix is simple, change the com.microsoft.azure.kusto.data.Utils

"HttpClient httpClient = HttpClients.createDefault();" 
to 
"HttpClient httpClient = HttpClients.createSystem();"

The fix will work when no proxy is used as well.

More info here:
https://stackoverflow.com/questions/5165126/without-changing-code-how-to-force-httpclient-to-use-proxy-by-environment-varia

**Comment by rjdkolb** [comment]
Created pull request:
https://github.com/Azure/azure-kusto-java/pull/30
