### ISSUE TITLE
ClientRequestProperties transfer parameters by JDK 11 issue

### ISSUE THREAD

**Issue by zujiaju** [Azure/azure-kusto-java#330]
**Describe the bug**
After execute kql with parameters by client request properties, there is an exception for "com/fasterxml/jackson/core/StreamReadConstraints."
The reason is the current ClientImpl only support Java 8,event the lastest verion(5.0.2).

**Expected behavior**
 upgrade the JDK version to 11.

**Screenshots**
The issue happend is below:
![Uploading 10_25_
![10_25_20](https://github.com/Azure/azure-kusto-java/assets/29225448/9eff9433-76d9-4ee2-921f-39bfabb3f8f7)
20.jpg…]()

**Desktop (please complete the following information):**

**Additional context**
Cause the HashMap created by Jdk 11, but need to decode by JDK 8.

**Comment by zujiaju** [comment]
![10_25_20](https://github.com/Azure/azure-kusto-java/assets/29225448/00306d7b-86b6-4e6d-a7ee-cdccbb79414f)

detail exception message:
2023-11-14 10:22:06.207 [http-nio-8207-exec-5 ] ERROR o.a.c.c.C.[.[.[/carmanage].[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/carmanage] threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/StreamReadConstraints] with root cause
java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/StreamReadConstraints
	at com.fasterxml.jackson.databind.util.TokenBuffer.<init>(TokenBuffer.java:64)
	at com.fasterxml.jackson.databind.SerializerProvider.bufferForValueConversion(SerializerProvider.java:491)
	at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:3527)
	at com.microsoft.azure.kusto.data.ClientRequestProperties.toJson(ClientRequestProperties.java:199)
	at com.microsoft.azure.kusto.data.ClientRequestProperties.toString(ClientRequestProperties.java:212)
	at com.microsoft.azure.kusto.data.ClientImpl.generateCommandPayload(ClientImpl.java:417)
	at com.microsoft.azure.kusto.data.ClientImpl.executeToJsonResult(ClientImpl.java:181)
	at com.microsoft.azure.kusto.data.ClientImpl.executeImpl(ClientImpl.java:134)
	at com.microsoft.azure.kusto.data.ClientImpl.lambda$execute$0(ClientImpl.java:115)
	at com.microsoft.azure.kusto.data.instrumentation.MonitoredActivity.invoke(MonitoredActivity.java:33)
	at com.microsoft.azure.kusto.data.ClientImpl.execute(ClientImpl.java:114)
	at com.qtsec.cloud.qtcsms.manage.config.AdxConfigure.executeKql(AdxConfigure.java:77)
	at com.qtsec.cloud.qtcsms.manage.service.impl.AdxServiceImpl.queryEventList(AdxServiceImpl.java:46)
	at com.qtsec.cloud.qtcsms.manage.service.impl.EventEvaluationServiceImpl.getEvaluationPage(EventEvaluationServiceImpl.java:77)
	at com.qtsec.cloud.qtcsms.manage.service.impl.EventEvaluationServiceImpl$$FastClassBySpringCGLIB$$e2fdca1a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
	at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)
	at com.qtsec.cloud.qtcsms.manage.service.impl.EventEvaluationServiceImpl$$EnhancerBySpringCGLIB$$747aa873.getEvaluationPage(<generated>)
	at com.qtsec.cloud.qtcsms.manage.controller.EventEvaluationController.getEvaluationPage(EventEvaluationController.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at com.qtsec.cloud.uc.sess.AuthenticationTokenFilter.doFilterInternal(AuthenticationTokenFilter.java:45)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by zujiaju** [comment]
Add exception message from snapshot:
Method threw 'java.lang.NoClassDefFoundError' exception. Cannot evaluate com.microsoft.azure.kusto.data.ClientRequestProperties.toString()

**Comment by yihezkel** [comment]
Hi @zujiaju,

This sounds like a conflict between dependency versions in your environment vs the dependency versions we support. We've tested this with Jackson v2.14.2.
- What version of Jackson is maven actually resolving in your project? (try `mvn dependency:tree` from your project's root)
- Have you tried using common ways to ensure your project actually uses Jackson v2.14.1, like [mvn exclude](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html#dependency-exclusions), https://maven.apache.org/plugins/maven-shade-plugin/ or https://plugins.jetbrains.com/plugin/7179-maven-helper ?

**Comment by The-Funk** [comment]
> Add exception message from snapshot: Method threw 'java.lang.NoClassDefFoundError' exception. Cannot evaluate com.microsoft.azure.kusto.data.ClientRequestProperties.toString()

If you are using a newer Jackson version like I am, I have a PR out to upgrade to 2.15.2 but it still needs formatting in order for the build to succeed.

**Comment by AsafMah** [comment]
PR #333 fixes this, We'll get out a new version soon

**Comment by The-Funk** [comment]
@zujiaju was this issue resolved for you with the Jackson upgrade?

**Comment by AsafMah** [comment]
Closing for now, @zujiaju feel free to respond and re-open.
